/* Autogenerated file. Do not edit manually. */
export type { GBVReportRegistry } from "./GBVReportRegistry";
export * as factories from "./factories";
export { GBVReportRegistry__factory } from "./factories/GBVReportRegistry__factory";
