/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GBVReportRegistry } from "./GBVReportRegistry";
export * as factories from "./factories";
export { GBVReportRegistry__factory } from "./factories/GBVReportRegistry__factory";
